version: 2
jobs:
  ruby-241:
    working_directory: /home/circleci/starling
    docker:
      - image: circleci/ruby:2.4.1-node
    steps: &common-steps
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: starling-{{ checksum "Gemfile.lock" }}

      # Update bundler
      - run: gem install bundler

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: starling-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run RSpec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Run Rubocop
      - type: shell
        command: |
          bundle exec rubocop

      # Run Reek
      - type: shell
        command: |
          bundle exec reek lib

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
  ruby-234:
    docker:
      - image: circleci/ruby:2.3.4-node
    working_directory: /home/circleci/starling
    steps: *common-steps
  ruby-227:
    docker:
      - image: circleci/ruby:2.2.7-node
    working_directory: /home/circleci/starling
    steps: *common-steps
workflows:
  version: 2
  test-all:
    jobs:
      - ruby-241
      - ruby-234
      - ruby-227